### ISSUE TITLE
Issue with eigen vector numbers in multiscale space function

### ISSUE THREAD

**Issue by LouisFaure** [dpeerlab/Palantir#10]
Hi,

First of all thank you for this tool, it works very nicely to uncover putative trajectories! I also experiemented using UMAP instead of t-SNE, which lead to similar interesting results as well!

But it seems there is an issue with the multiscale space function, it sometimes outputs an empty ms_data when automatic selection of n_eig is performed. In case I use a defined n_eigs, choosing any value will lead to a ms_data that will always have one less dimension than the parameter, so using n_eig=1 will also lead to an empty dataset. 

By doing a quick look at the code I found what would explain what I am seeing:
`use_eigs = list(range(1, n_eigs))`
Having a 1 means that it obviously ignore the first column of Eigenvalues in the next lines. Is there a reason why we are ignoring it?

Thanks in advance for your help!

Louis

**Comment by ManuSetty** [comment]
Thank you for interest in Palantir and I am glad you get good results! 

In diffusion maps, the first Eigen vector is a trivial Eigen vector or the stationary distribution. You can examine the Eigen gap and use number of Eigen vectors > 1 for the analysis.

**Comment by LouisFaure** [comment]
Thank you very much for the fast answer, now I understand why! 

I think it would be nice to add a warning when the automatic selection of n_eig lead to an empty multiscaled dataset, or a dataset of dimension 1. Because my initial issue was that a tsne was still produced even with an empty dataset, leading to a random scatter plot of all the cells.

**Comment by ManuSetty** [comment]
Sure - I have updated the notebook. Thanks for the pointer!
