### ISSUE TITLE
Adjust x-axis for pseudotime gene expression plots

### ISSUE THREAD

**Issue by andrewsong777** [dpeerlab/Palantir#134]
Hello,
I am trying to adjust the x-axis for the gene expression plots across pseudotimes:
genes = ['BASP1', 'CD9', 'DLG2', 'FNBP1', 'FRMD3', 'IL11RA', 'IQCE', 'KCNQ3', 'TOX2', 'BSG', 'CCDC125',
         'GABRB3', 'GNB2L1', 'HAPLN4', 'HEBP2', 'HSD17B12']

#ISGF10
fig, ax = palantir.plot.plot_gene_trends(ad, genes)
ax.set_xlabel('Pseudotime')  # Set the x-axis label
ax.set_xlim([0, 0.45])  # Set the desired x-axis limits
plt.show()

<img width="979" alt="Screenshot 2024-02-20 at 2 49 30 PM" src="https://github.com/dpeerlab/Palantir/assets/157518103/16e9cf21-fcc1-498f-9990-6cb52690768f">

My error message is pasted.

**Comment by katosh** [comment]
Hello @andrewsong777,

Thank you for bringing this to our attention. The `plot.plot_gene_trends` function indeed returns a figure object, and the axes within it are generated iteratively in a loop. Consequently, direct access to the axes for modifications like setting the x-axis label isn't provided in a straightforward manner. However, you can still access and manipulate the axes by using the `fig.get_axes()` method on the returned figure object. Here's how you can set the x-axis label to "Pseudotime" for each subplot:

```python
import matplotlib.pyplot as plt
import palantir

fig = palantir.plot.plot_gene_trends(ad, genes)
for ax in fig.get_axes():
    ax.set_xlabel("Pseudotime")

# Adjust the layout to prevent any overlap
plt.tight_layout()

plt.show()
```

This approach ensures that each subplot within the figure has its x-axis labeled as "Pseudotime", and `plt.tight_layout()` adjusts the spacing to make the plot more readable. Let me know if you have any further questions or issues!

**Comment by andrewsong777** [comment]
Thank you! What are the units for the y-axis? Is it average read counts?

**Comment by katosh** [comment]
I would just refer to it as a _gene-expression level_. Its values can be compared within a gene but its unit is hard to pin down and depends a lot on its processing, e.g., the normalization strategy, and the pseudo-count in the log-transformtion.

To compute the trend line we use a [Gaussian Process](https://distill.pub/2019/visual-exploration-gaussian-processes/) to find the "best" smooth function that could have generated the measured gene-expression levels under some assumptions about the noise of these measurements `sigma` and the smoothness of this function `ls`. We use [Mellon's FunctionEstimator](https://mellon.readthedocs.io/en/latest/model.html#mellon.model.FunctionEstimator) to find this function (also s. [this tutorial](https://mellon.readthedocs.io/en/latest/notebooks/trajectory-trends_tutorial.html)). Unlike simple moving averages, this approach can predict values outside the observed range, accommodating for potential peaks between data points.
