### ISSUE TITLE
ImportError: cannot import name 'config' from 'jax.config' (/home/william/mambaforge/envs/palantir/lib/python3.12/site-packages/jax/config.py)

### ISSUE THREAD

**Issue by wbrett87** [dpeerlab/Palantir#136]
Hello! 

Upon creating a new conda environment and installing the newest Palantir version using pip, I get the following error after importing palantir in jupyter: 

![image](https://github.com/dpeerlab/Palantir/assets/103341754/1bddb6ac-9b5d-4ae3-93a9-5e01d65a6c33)

Any help would be greatly appreciated!

**Comment by katosh** [comment]
This seems to be a change of the jax library that broke the dependency Mellon. I will make a new version of Mellon soon. For a quick fix you can install it from the current main branhc by
```bash
pip install --upgrade 'git+https://github.com/settylab/Mellon.git'
```

Please let me know if this does not fix the issue or if you have any further questions!

**Comment by katosh** [comment]
This can be traced back to the deprecation of `jax.config.config` in [jax v0.4.25](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-25-feb-26-2024) just two days ago. I finished a new release of [Mellon v1.4.2](https://github.com/settylab/Mellon/releases/tag/v1.4.2) which is available through conda and pypi with
```bash
pip install --upgrade mellon
```

**Comment by wbrett87** [comment]
Wow thanks for the quick action. This fixed it!
