### ISSUE TITLE
unable to repeat the results in multiple runs

### ISSUE THREAD

**Issue by MichaelPeibo** [dpeerlab/Palantir#14]
Hi, 

I just found in every single run without changing parameters, the diffusion map will be different, even though I set `random.seed(100)` (if that is the function of random.seed).

Any suggestion how to avoid this? Or just some bug produced in my own case?

Thanks!

**Comment by MichaelPeibo** [comment]
an UPDATE: I have to restart kernel and clear all to repeat it.

**Comment by ManuSetty** [comment]
Is this query about the reproducibility of the tSNE maps built on diffusion maps ?

**Comment by MichaelPeibo** [comment]
@ManuSetty , I just found I need to restart kenel to maker sure I can reproduce results.

**Comment by MichaelPeibo** [comment]
Sorry to bother again.

I have an issue to repeat t-sne projections of cells(even restarting kernel), is there any parameters to set up to keep the reproducibility?

**Comment by ManuSetty** [comment]
Did the ```random.seed``` not help?

**Comment by MichaelPeibo** [comment]
Nope..

Here is snapshot of what I did:
```
import random
random.seed(100)
code to produce tsne projection
```
first time I got layout below:

![1](https://user-images.githubusercontent.com/32219336/60142751-d2ba9f80-97ed-11e9-8d08-691125e5091f.png)

Then I restart kernel, I reran it and got layout below:
![2](https://user-images.githubusercontent.com/32219336/60142784-e9f98d00-97ed-11e9-95a5-5f06cd1a2183.png)

**Comment by ManuSetty** [comment]
This is a bit surprising. Are you setting the random seed after importing all the packages ?

**Comment by ManuSetty** [comment]
Hello 

In some recent experiments, we found that rather than `random.seed`, setting `np.random.seed` gave reproducible results. Can you please give it a try.

**Comment by ManuSetty** [comment]
Closing the issue since the solution above can yield consistent results

**Comment by katosh** [comment]
This one was fixed within Palantir here: https://github.com/dpeerlab/Palantir/commit/f4970f9f0571edfed486232acb68d2f0a8c26543
