### ISSUE TITLE
Why is ms_data empty?

### ISSUE THREAD

**Issue by st4302** [dpeerlab/Palantir#147]
I am running palantir on 2 different cell types from my adata object that I have processed with scanpy. I subset the adata object based on cell types. For the T cells the analysis seems to work. However, for the B cells it fails.  I run the analysis like shown below.

```Python
# Run diffusion maps
dm_res = palantir.utils.run_diffusion_maps(b_cells_adata, n_components=5)
ms_data = palantir.utils.determine_multiscale_space(b_cells_adata)
#UMAP visualization
sc.pp.neighbors(b_cells_adata)
sc.tl.umap(b_cells_adata)
# Use scanpy functions to visualize umaps or FDL
sc.pl.embedding(
    b_cells_adata,
    basis="umap",
    frameon=False,
)
imputed_X = palantir.utils.run_magic_imputation(b_cells_adata)
palantir.plot.plot_diffusion_components(b_cells_adata)
plt.show()

start_cell = "TCAATTTAGATGGGCT-1"
pr_res = palantir.core.run_palantir(
    b_cells_adata, start_cell, num_waypoints=500)
```

I realized that the reason it fails is because ms_data is empty when I run the code for the B cells. What could be causing this issue?

Thank you

**Comment by katosh** [comment]
Hi @st4302, thank you for your inquiry. This sounds like no eigenvectors are selected based on the eigen-gap selection method implemented. You might be able to fix this by using more diffusion components in the first place `n_components`. However, if you want to avoid using the automated eigenvector selection you can specify `n_eigs` in the `determine_multiscale_space` instead to a positive integer smaller than `n_components`.

Please let me know if you have any questions about that or if this solves the problem.

**Comment by st4302** [comment]
Hello,

Thank you for your fast reply. I tried ms_data = palantir.utils.determine_multiscale_space(b_cells_adata, n_eigs=2) and that seems to work. 
I am just trying to understand what does the fact that the original command does not work for the B cells but works for the T cells indicate about the data that I have?

**Comment by katosh** [comment]
The eigenvalue gap method relies on the fact that biological processes and technical variability have different magnitudes and that there is a clear gap between them. However, if only 5 components are computed to start with, then there is a high chance they are all biologically driven and the largest gap of their magnitudes is just random. It should never fail to compute and we will consider changing the implementation to always at least use 2 eigenvectors, however, you might get better results by including more components in the `run_diffusion_maps` step.

I am glad this worked. Please don't hesitate to ask further questions even after I close this issue.

**Comment by st4302** [comment]
Thank you so much for your help.  When running 
```
dm_res = palantir.utils.run_diffusion_maps(b_cells_adata, n_components=10)
ms_data = palantir.utils.determine_multiscale_space(b_cells_adata)
``` 
the ms_data is still empty. However,  running
```
dm_res = palantir.utils.run_diffusion_maps(b_cells_adata, n_components=5)
ms_data = palantir.utils.determine_multiscale_space(b_cells_adata, , n_eigs=2) 
```
seems to create an ms_data object with dimensions (872, 1) which can then be used for the trajectory analysis. 
Is it better to increase  n_eigs=3 so I can get dimensions (872,2)?
Also, I just want to doublecheck but in the `palantir.utils.determine_multiscale_space` we are supposed to use the adata object not the dm_res one right?

**Comment by katosh** [comment]
Yes, I agree that just one dimension is quite low and it will likely be hard to capture the complete biological variability through just that. I would increase the `n_eigs` to see if a more detailed result is possible. Then, maybe the eigen-gap method is not the best approach for your data, or there might be a clearer gap after 10 components, so, one could increase `n_components` further.

Also, the dimension is 1 lower than `n_eigs` because the first eigenvector is always discarded since it should always be almost constant.
