### ISSUE TITLE
Shape mismatch in terminal cluster identification

### ISSUE THREAD

**Issue by concatenize** [dpeerlab/Palantir#16]
Hi Palantir team,

Great work on this tool -- I hope you are getting a positive response!

I am getting a persistent error during terminal cluster identification:

    shape mismatch: value array of shape (0,1152) could not be broadcast to indexing result of shape (0,)

The value varies but it's always been between 1100 and 1200. 

I suspect this is happening because the set of absorbing states is coming up empty. The traceback points to line 371 in `palantir/core.py`, which does `T[abs_states, :] = 0` inside a function called `_differentiation_entropy`.

Right now, I am testing palantir on confidential data, so I can't share the exact example, but if I have time to reproduce the code on public data, I'll post here again.

**Comment by concatenize** [comment]
The error seems very robust: it happens with `use_early_cell_as_start=False` or `use_early_cell_as_start=True`, with or without specifying terminal cells, and with multiple root cells.

**Comment by ManuSetty** [comment]
Thank you for your interest in Palantir! 

Can you please confirm that you get this error even when you specify the terminal states? 

Can you also provide some more information about the data: How many cells, genes and how you are selecting the genes for analysis?

**Comment by concatenize** [comment]
Yes, I get the error even when I specify some terminal states. I am analyzing 54k cells using the Harmony vignette as a starting point. Briefly, I selected 1119 genes using Seurat, normalized the cells to 10k UMIs each, logged with a pseudocount of 0.1, then ran `harmony.core.augmented_affinity_matrix` with 65 PC's.  I called `palantir.utils.run_diffusion_maps`
and `palantir.utils.determine_multiscale_space`, which produced a 4D embedding, and that's my input for `palantir.core.run_palantir`. 

I would like to anonymize the data and post an example, but when I save it to csv and load it again, I don't see the same error. I will post again if/when I am able to create a reproducible example.

**Comment by concatenize** [comment]
OK, I think I've got it. In this demo, the error consistently happens when `scanpy` is imported, and otherwise the error does not happen. Does this work for you?

I am not a Python regular, so this bug caught me off guard -- I thought all Python packages would have separate namespaces and would be unable to interfere with one another.

```
# scRNA tools
import harmony
import palantir
import scanpy.api as sc

# Plotting and miscellaneous imports
import os
import pandas as pd
demo_path = os.path.expanduser("~/Desktop/demo_data_smol.csv.txt")
demo_data = pd.read_csv(demo_path, index_col = 0).iloc[0:500, :]
pr_res = palantir.core.run_palantir(demo_data, demo_data.index[0], [demo_data.index[400]], n_jobs = 1)
```

[demo_data_smol.csv.txt](https://github.com/dpeerlab/Palantir/files/3350930/demo_data_smol.csv.txt)






Here are my package versions from `pip freeze`.

```
anndata==0.6.20
appnope==0.1.0
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
cffi==1.12.3
Click==7.0
cmake==3.14.4
cycler==0.10.0
Cython==0.29.7
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
fa2==0.3.5
fcsparser==0.2.0
h5py==2.9.0
harmony==0.1.1
importlib-metadata==0.18
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
kiwisolver==1.1.0
llvmlite==0.28.0
MarkupSafe==1.1.1
matplotlib==3.1.0
mistune==0.8.4
mock==3.0.5
more-itertools==7.1.0
MulticoreTSNE==0.1
natsort==6.0.0
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numba==0.43.1
numexpr==2.6.9
numpy==1.16.3
packaging==19.0
palantir==0.2.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
patsy==0.5.1
pexpect==4.7.0
PhenoGraph==1.5.2
pickleshare==0.7.5
pip-tools==3.7.0
pluggy==0.12.0
POT==0.5.1
prometheus-client==0.6.0
prompt-toolkit==2.0.9
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pycparser==2.19
Pygments==2.4.2
pyparsing==2.4.0
pyrsistent==0.15.2
pytest==5.0.0
python-dateutil==2.8.0
pytz==2019.1
pyzmq==18.0.1
rpy2==3.0.4
scanpy==1.4.3
scikit-learn==0.21.2
scipy==1.3.0
seaborn==0.9.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.12.0
sklearn==0.0
statsmodels==0.9.0
tables==3.5.1
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
tqdm==4.32.1
traitlets==4.3.2
tzlocal==1.5.1
umap-learn==0.3.9
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wot==1.0.2
zipp==0.5.1
```

**Comment by ManuSetty** [comment]
This unfortunately seems to be an issue with `scanpy` : https://github.com/theislab/anndata/issues/159 which is breaking the `scipy sparse` interface used in Palantir. 

Can you try not importing scanpy until after you have the Palantir results ? Alternatively, you can also try downgrading scipy as suggested in the link above.

**Comment by concatenize** [comment]
Yes, I will run palantir in a separate notebook without loading scanpy.
