### ISSUE TITLE
Is there a way to set the alpha parameter in the diffusion map?

### ISSUE THREAD

**Issue by davisidarta** [dpeerlab/Palantir#17]
Hi! Great package! Especially great kernel and multispace scaling!

I wonder if there is a way to set the alpha parameter when `runni.ng run_diffusion_maps`, as one may wish to get the Laplace-Beltrami operator to perform dimensionality reduction with, or do so in a Fokker-Planck fashion. I'm trying to perform some tests on how this could affect the embedding results.

Besides, is any way to implement this kernel with faster diffusion maps implementations, such as PyDiffMap or DMaps?

**Comment by ManuSetty** [comment]
Thank you for the interest in Palantir!

We are testing out a faster implementation using approximate nearest neighbors and will make sure to respond to this thread when the release is ready. 

The alpha parameter is currently not available but will add it as a parameter to `run_diffusion_maps` function.

**Comment by ManuSetty** [comment]
I have pushed an updated version to master which exposes the alpha parameter and significantly speeds up nearest neighbor computation. Please update the repository and give it a try.

**Comment by davisidarta** [comment]
Thank you Dr. Setty! I appreciate the update. However, when running it, I get an error:

```
  IndexError: index 5 is out of bounds for axis 0 with size 0

Detailed traceback: 
  File "<string>", line 29, in <module>
  File "/usr/local/lib/python3.6/dist-packages/palantir/utils.py", line 55, in run_diffusion_maps
    adaptive_std[i] = np.sort(kNN.data[kNN.indptr[i]:kNN.indptr[i + 1]])[adaptive_k - 1]
```

I'm running it on a data-frame that previously worked with palantir. I'm unsure if this has to do with any dependencies updates. I'm running this on reticulate with RStudio, python 3.6.8 and R 3.6.1.

**Comment by ManuSetty** [comment]
Can you please provide a bit more information about the data and the parameter setting used. The data dimensions and the number of components in the multi-scaled space will be helpful in debugging this.
