### ISSUE TITLE
phenograph error during install

### ISSUE THREAD

**Issue by sroyyors** [dpeerlab/Palantir#20]
hi,
I am trying to install this via conda using 
_pip install ._

But I get the following error
_"Collecting phenograph (from palantir==0.2.1)
  ERROR: Could not find a version that satisfies the requirement phenograph (from palantir==0.2.1) (from versions: none)
ERROR: No matching distribution found for phenograph (from palantir==0.2.1)_

I tried to install this directly from git as mentioned in setup.py, but I am not sure if it worked because subsequently I got a segmentation fault while trying the test example in the 
_dm_res = palantir.utils.run_diffusion_maps(pca_projections, n_components=5)_
command

**Comment by ManuSetty** [comment]
Hello 

Could you please try installing Phenograph from here: https://github.com/dpeerlab/PhenoGraph and see if it resolves the issue?

**Comment by sroyyors** [comment]
hi Manu,
no I still get the issue. I installed phenograph from the above url, commented the "phonograph" package in the install file and installation went through fine (which it had previously), but it failed to again run the diffusion map. Here is what happens (I normalize counts and log transform, following the example in https://nbviewer.jupyter.org/github/dpeerlab/Palantir/blob/master/notebooks/Palantir_sample_notebook.ipynb#palantir).

 _dm_res = palantir.utils.run_diffusion_maps(pca_projections, n_components=5)
Determing nearest neighbor graph...
Segmentation fault (core dumped)_

Can I run palantir in more verbose mode?

**Comment by ManuSetty** [comment]
Unfortunately, there is no further verbose option. 

This looks like an issue that is not related to Phenograph since that package is not used in the computation where this is failing. The nearest neighbor graph is computed using ``scanpy``.  Can you please let me know what version of python, scanpy, scipy, numpy and pandas you are using?

**Comment by sroyyors** [comment]
I am using python=3.7.4, scipy=1.3.1, numpy=1.16.5.
I don't see pandas in my conda environment.
For scanpy, it should have been what is in the setup.py. But I did not specify a specific version. If I  check the version, it seems to be 1.4.4.post1.

Here is my conda env for palantir.

name: palantir4
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - intel-openmp=2019.5=281
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.5=py37h7e9f1db_0
  - numpy-base=1.16.5=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_1
  - pip=19.2.2=py37_0
  - python=3.7.4=h265db76_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
prefix: /mnt/ws/sysbio/roygroup/home/sroy/old-local-home/miniconda2/envs/palantir4

**Comment by ManuSetty** [comment]
I have numpy version 1.71.1 but I do not think that should matter. However, I am surprised you do not have pandas in the environment since it is a key dependency for Palantir and is specified in the setup file. Perhaps, trying to install pandas manually will help?

**Comment by sroyyors** [comment]
actually I just manually installed scanpy and it added pandas.
The error seems to be with scanpy, failing in line 41 of utils.py
 temp = sc.AnnData(data_df.values)

I'll see if I can figure this out

**Comment by sroyyors** [comment]
good news! I was able to get it to work. Turns out that scanpy was using an older (default package) of matplotlib. I had to manually set PYTHONUSERBASE to the site_packages path of the conda environment.

**Comment by ManuSetty** [comment]
Ok great - glad to hear it all worked out!
