### ISSUE TITLE
it seems a little bug in this line

### ISSUE THREAD

**Issue by dhtc** [dpeerlab/Palantir#22]
Thanks for sharing the great package. 
But i found a little bug in this line:
https://github.com/dpeerlab/Palantir/blob/57069e26c1e6115b8319cee11cba0553fd3b1ef8/src/palantir/presults.py#L60
the key for branch_prob should be '_branch_probs', you might miss the 's'

**Comment by ManuSetty** [comment]
Thank you! Fixed in 35d159b3056420170da69e005516564fbc740722
