### ISSUE TITLE
Don’t install things in setup.py

### ISSUE THREAD

**Issue by flying-sheep** [dpeerlab/Palantir#25]
This is not how you do it and can seriously annoy people. I for one am happy I didn’t blindly install this to be bitten by this misbehavior. Specify dependecies as dependencies (`install_requires`) instead.

https://github.com/dpeerlab/Palantir/blob/6168f60c0ea416d87d622fccb0c0709dde2cc88c/setup.py#L19

**Comment by ManuSetty** [comment]
Yes - completely agree. Meant to do this a while ago and thanks for pointing out. Fixed in 73b209b5ac6ffb1fa763d3f5a5f4602bdf65c0d0

**Comment by flying-sheep** [comment]
Thank you. I think with #26 it could be even more convenient.
