### ISSUE TITLE
can I transfer cell identity from Seurat to Palantir

### ISSUE THREAD

**Issue by liuweihanty** [dpeerlab/Palantir#36]
Dear Palantir team,
I used Seurat to cluster and label the identity of my cells, and would love to use your tool to do trajectory analysis. I'm wondering is there anyway to transfer the cell identity information from Seurat to Palantir? Thanks!

**Comment by millersan** [comment]
######
a<-@assays$RNA@counts
write.csv(a,"sample_scseq_counts.csv",sep="\t")
######
I think you can try something like this?

**Comment by liuweihanty** [comment]
Thank you very much! Sorry what I mean is the identity column of the cell clusters I stored in the Seurat metadata, for example, Neutrophil, monocyte etc.. I know we can do the cell cluster identification by marker expression in palantir, but since I already did that in Seurat, just wondering can I transfer this information into palantir. Thanks!

**Comment by ManuSetty** [comment]
Hello! Apologies in the delay for getting back to you. 

Can you please let me know how you want to use the cell cluster information in Palantir? For example, is it to compute trends? If that is the case, you can manually set the ```terminal_states``` parameter to the cell types of interest.
