### ISSUE TITLE
publication cell types

### ISSUE THREAD

**Issue by igordot** [dpeerlab/Palantir#40]
I was trying to retrieve the data from the Nature Biotechnology paper. The data directory contains the expression values and the tSNE coordinates. However, I cannot locate the cell type labels (as shown in Fig. 1a or Fig. 2b). Where can I find those?

**Comment by ManuSetty** [comment]
We will update the anndata objects to include the cell types. In the mean time, the cluster to cell type mapping for each replicate is listed below 

```
Rep1
cluster_annotations = pd.Series([])
cluster_annotations[0] = 'Hematopoietic stem cells'
cluster_annotations[1] = 'Hematopoietic multipotent progenitors'
cluster_annotations[2] = 'Erythroid progenitors'
cluster_annotations[3] = 'Monocyte progenitors'
cluster_annotations[4] = 'Myeloid progenitors'
cluster_annotations[5] = 'Common lymphoid progenitors'
cluster_annotations[6] = 'Monocyte progenitors'
cluster_annotations[7] = 'Dendritic cell progenitors'
cluster_annotations[8] = 'Erythroid progenitors'
cluster_annotations[9] = 'Megakaryocyte progenitors'

Rep2
cluster_annotations = pd.Series([])
cluster_annotations[0] = 'Hematopoietic stem cells'
cluster_annotations[1] = 'Hematopoietic multipotent progenitors'
cluster_annotations[2] = 'Erythroid progenitors'
cluster_annotations[3] = 'Myeloid progenitors'
cluster_annotations[4] = 'Monocyte progenitors'
cluster_annotations[5] = 'Dendritic cell progenitors'
cluster_annotations[6] = 'Erythroid progenitors'
cluster_annotations[7] = 'Common lymphoid progenitors'
cluster_annotations[8] = 'Dendritic cell progenitors'
cluster_annotations[9] = 'Megakaryocyte progenitors'

Rep3 
cluster_annotations = pd.Series([])
cluster_annotations[0] = 'Common lymphoid progenitors'
cluster_annotations[1] = 'Hematopoietic multipotent progenitors'
cluster_annotations[2] = 'Hematopoietic stem cells'
cluster_annotations[3] = 'Monocyte progenitors'
cluster_annotations[4] = 'Dendritic cell progenitors'
cluster_annotations[5] = 'Erythroid progenitors'
cluster_annotations[6] = 'Myeloid progenitors'
cluster_annotations[7] = 'Monocyte progenitors'
cluster_annotations[8] = 'Megakaryocyte progenitors'
cluster_annotations[9] = 'Dendritic cell progenitors'
```

**Comment by igordot** [comment]
But which cells correspond to which clusters? Are the cluster labels available somewhere?

**Comment by ManuSetty** [comment]
Clusters are available in the ```anndata``` objects here: https://github.com/dpeerlab/Palantir#processed-data-and-metadata

```ad.obs['clusters']```

**Comment by igordot** [comment]
Thank you for the clarification! I didn't realize those links were pointing to files outside of the repo. I assumed the `data` directory contained everything.

**Comment by cakeinspace** [comment]
But in Rep1 annotations that you provide you have mentioned erythroid progenitors and monocyte progenitors twice. Shouldnt they be different because the number of unique clusters then is lower than 9

**Comment by ManuSetty** [comment]
I believe in this case, multiple clusters were annotated as the same cell-type and hence the apparent discrepancy.
