### ISSUE TITLE
PackageNotInstalledError: The R package "gam" is not installed.

### ISSUE THREAD

**Issue by zmokhtari** [dpeerlab/Palantir#45]
Hi,
Even though I have installed "gam" in R, I still face this issue: "PackageNotInstalledError: The R package "gam" is not installed " when I try to determine the gene expression trends. Would it be possible to use "pygam" instead of "gam" from R?

Thanks,
Zeinab

**Comment by ManuSetty** [comment]
Could you perhaps check if the R installation on the path picked up by python is correct. The best way to ensure this is to set the  ```R_HOME``` bash environment variable. You can also do this within your Jupiter notebook use  ```%env R_HOME=<path_to_R>```

In our initial testing, ```pygam``` did not give us the most stable results. But we will add an option to us ```pygam``` as a fallback if ```R gam``` is not available.

**Comment by zmokhtari** [comment]
Thank you very much for your help. The issue is resolved.
