### ISSUE TITLE
PhenoGraph multi-processing error

### ISSUE THREAD

**Issue by team-tomato-salad** [dpeerlab/Palantir#46]
Hi,

I was trying to use Palantir.presults.cluster_gene_trends funtion and run into a Type Error showing- "expected list, got np.ndarray". The function worked perfectly before the scanpy update, and I also updated Palantir package. I also followed the latest Palantir tutorial notebook. 

> /usr/lib/python3.8/site-packages/scipy/sparse/lil.py in tocsr(self, copy)
    475         indices = np.empty(nnz, dtype=idx_dtype)
    476         data = np.empty(nnz, dtype=self.dtype)
--> 477         _csparsetools.lil_flatten_to_array(self.rows, indices)
    478         _csparsetools.lil_flatten_to_array(self.data, data)

> _csparsetools.pyx in scipy.sparse._csparsetools.lil_flatten_to_array()

> _csparsetools.pyx in scipy.sparse._csparsetools._lil_flatten_to_array_int32()

> TypeError: Expected list, got numpy.ndarray

The issue was fixed by setting n_job parameter to 1. I am not sure why n_job -1 would cause the issue and would like to know if this issue happens on other systems.

Thank you for your time!

**Comment by ManuSetty** [comment]
Thanks for bringing this to our attention. This looks like an issues with ```scipy``` and more details are here: https://github.com/dpeerlab/PhenoGraph/issues/4.

**Comment by hisplan** [comment]
@team-tomato-salad we have just released PhenoGraph v1.5.7. Please try again with this version.

**Comment by hisplan** [comment]
Please reopen if you have any issue.
