### ISSUE TITLE
Error in palantir.utils.run_magic_imputation 

### ISSUE THREAD

**Issue by carloelle** [dpeerlab/Palantir#48]
Hi, when I run your [tutorial](https://nbviewer.jupyter.org/github/dpeerlab/Palantir/blob/master/notebooks/Palantir_sample_notebook.ipynb) on Palantir using your data, I run into this error when running magic imputation: 
`imp_df = palantir.utils.run_magic_imputation(ad, dm_res)` 
it results in: 
`Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    imp_df = palantir.utils.run_magic_imputation(ad, dm_res)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/palantir/utils.py", line 123, in run_magic_imputation
    data = pd.DataFrame(data.X.todense(), index=data.obs_names, columns=data.var_names)
AttributeError: 'numpy.ndarray' object has no attribute 'todense'`

any idea how to resolve this issue and get `imp_df` computed?
I'm using python 3.8

anndata     0.7.4
harmony     0.1.4
matplotlib  3.3.3
numpy       1.19.2
palantir    1.0.0
pandas      1.1.4
scanpy      1.6.0
sinfo       0.3.1
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.7.0
jupyterlab          2.2.9
notebook            6.1.5
Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
macOS-10.16-x86_64-i386-64bit
4 logical CPU cores, i386
Session information updated at 2020-11-24 09:48

**Comment by carloelle** [comment]
Ps: I think the error is generated because it is looking for a dense matrix but `dm_res` is a sparse matrix. I tried with `dm_res.todense()` following this [suggestion](https://stackoverflow.com/questions/16505670/generating-a-dense-matrix-from-a-sparse-matrix-in-numpy-python) but with no success, since it results in this error:
`Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    dm_res.todense()
AttributeError: 'dict' object has no attribute 'todense'`

**Comment by ManuSetty** [comment]
Thanks for pointing this out. We will put in a fix.

In the meantime, can you try the following before running Imputation 
```
from scipy.sparse import csr_matrix
ad.X = csr_matrix(ad.X)
```
 This will ensure the data matrix is sparse which seems to the issue here.
