### ISSUE TITLE
Installation problem: failed building wheel for llvmlite

### ISSUE THREAD

**Issue by sruthi-hub** [dpeerlab/Palantir#50]
I have been facing multiple issues with the installation of Palantir. Currently, I have created a virtual environment, and I am trying to get the package installed within. 

python 2.9
pip 20.3.3
Linux machine

Since I was getting an error "Failed building wheel for llvmlite", I tried to install it separately, using: "easy_install llvmlite.
And this worked! (image here)
![image](https://user-images.githubusercontent.com/51859127/104023038-15a15580-518f-11eb-9813-6439b0e96e72.png)

Error I am facing:

![image](https://user-images.githubusercontent.com/51859127/104023315-7892ec80-518f-11eb-9a71-27838f76d9c1.png)

![image](https://user-images.githubusercontent.com/51859127/104023400-9eb88c80-518f-11eb-8d55-975717bf4724.png)

![image](https://user-images.githubusercontent.com/51859127/104023141-349fe780-518f-11eb-93d3-35692edcf26a.png)

![image](https://user-images.githubusercontent.com/51859127/104023202-4b463e80-518f-11eb-929c-7fbbfb8cac4c.png)

![image](https://user-images.githubusercontent.com/51859127/104023258-631dc280-518f-11eb-8d11-eadcc1cf07f2.png)

**Comment by ManuSetty** [comment]
We do not support python2.9. Can you please upgrade to python 3.7+ and try again ?

**Comment by sruthi-hub** [comment]
Sorry, that was a typo. 
My python version is 3.9.1.

It still doesn't work.

**Comment by ManuSetty** [comment]
Thanks for the clarification. I was able to reproduce your error and this looks to be an issue in installing the ``numba`` package, which is not yet supported in python3.9: https://github.com/numba/numba/issues/6345. My recommendation would be to use python3.8.

**Comment by sruthi-hub** [comment]
Thank you so much! That worked!
