### ISSUE TITLE
Value error: Did not find adata.var['highly_variable'] when it is actually present

### ISSUE THREAD

**Issue by sruthi-hub** [dpeerlab/Palantir#51]
I am using palantir and scanpy for trajectory inference in single-cell RNA-seq dataset.
There is some issue with computing Palantir diffusion maps.
1. It gives me an error that is did not find adata.var['highly_variable'] when it is already present.
2. It gives an error, that 'n_components' is not a valid argument, when it is.

Python 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-redhat-7.8-Maipo
16 logical CPU cores, x86_64

palantir version 1.0.0

![image](https://user-images.githubusercontent.com/51859127/104649501-d4bfaa00-5682-11eb-91bd-78675afa6a90.png)

**Comment by ManuSetty** [comment]
Similar to issue #52 , this might be related to scanpy version as well. As with #52 , please use the release candidate version of scanpy `pip install scanpy==1.7.0rc1`

**Comment by sruthi-hub** [comment]
> Similar to issue #52 , this might be related to scanpy version as well. As with #52 , please use the release candidate version of scanpy `pip install scanpy==1.7.0rc1`

Thank you so much for your help! @ManuSetty
