### ISSUE TITLE
Error running 'sce.tl.palantir(adata)'

### ISSUE THREAD

**Issue by sruthi-hub** [dpeerlab/Palantir#52]
I am using palantir and scanpy for trajectory inference in single-cell RNA-seq dataset.
There is some issue with computing Palantir diffusion maps.
1. It gives me an error that is did not find adata.var['highly_variable'] when it is already present.
2. It gives an error, that 'n_components' is not a valid argument, when it is.

Python 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-redhat-7.8-Maipo
16 logical CPU cores, x86_64

palantir version 1.0.0

![image](https://user-images.githubusercontent.com/51859127/104649501-d4bfaa00-5682-11eb-91bd-78675afa6a90.png)
![image](https://user-images.githubusercontent.com/51859127/104649986-8959cb80-5683-11eb-86c4-9020a1536897.png)

**Comment by ManuSetty** [comment]
Thanks for pointing this out to us. The `n_components` parameter is unfortunately not exposed through the scanpy interface. Could you please try using the stand along Palantir python package.

**Comment by ManuSetty** [comment]
Hello again. My colleague @awnimo just pointed that this a scanpy version issue. The Palantir interface with `n_components` exposed is still in the pre-release stage and can be installed using `pip install scanpy==1.7.0rc1`
