### ISSUE TITLE
Gene expression trends plot could we have a COLORBAR?

### ISSUE THREAD

**Issue by sruthi-hub** [dpeerlab/Palantir#54]
Hello, 
Thanks for the great package! 
I'm wondering if we could have a color bar indicating the expression levels in:
palantir.plot.plot_gene_expression(imp_df, fdl, *Marker Genes*)
Thanks!

![image](https://user-images.githubusercontent.com/51859127/105531422-474e0c80-5cb7-11eb-8b04-c1f912ebcdb7.png)

**Comment by sruthi-hub** [comment]
Hello, 
Just wanted to follow-up on this. Is there an easy fix using matplotlib or seaborn to add colorbar? 

Another customization question:
Is there any parameter to increase the distance between the plots in palantir.plot.plot_palantir_results(pr_res, fdl) ?
These tend to overlap on each other.

**Comment by ManuSetty** [comment]
Color bar can be added to the plots by setting the `plot_scale` parameter to `True`.
