### ISSUE TITLE
Font issue and no plot result in scanpy

### ISSUE THREAD

**Issue by YubinXie** [dpeerlab/Palantir#55]
Hi, I constantly have issue on font. Any tip to install these fonts? And my scanpy plot function has no output after loading Palantir:

```
findfont: Font family ['Raleway'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Lato'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Bitstream Vera Sans'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Bitstream Vera Sans'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Bitstream Vera Sans'] not found. Falling back to DejaVu Sans.
```

`%matplotlib inline` has to be added to recover the inline plot function. Not sure if they are related but Palantir could have been removing the original `%matplotline inline` function

**Comment by ManuSetty** [comment]
The font dependencies have been updated in 2956a07935a28a4b7e33bde5fd4b3684ce66ab67
