### ISSUE TITLE
About running Palantir using cisTopic object

### ISSUE THREAD

**Issue by nigred** [dpeerlab/Palantir#57]
Hello. I would like to run Palantir using cisTopic object by following the methods described under "Pseudotime Inference" from Ma et al., 2020 (Volume 183, Issue 4, 12 November 2020, Pages 1103-1116.e20). Where could I find a detailed method of this section of the journal article? If possible, may I have a detailed method for running Palantir using cisTopic object? 

Thank you for your help.

**Comment by ManuSetty** [comment]
Cistopic is a tool developed by the Stein Arts lab and can be found here: https://github.com/aertslab/cisTopic
