### ISSUE TITLE
sns.set in Palantir conflicts with scanpy heatmap + marker tree plot function

### ISSUE THREAD

**Issue by YubinXie** [dpeerlab/Palantir#58]
In the Palantir, one of the setting is causing issues in the plot function in scanpy: 
The code:
```with warnings.catch_warnings():
    # catch experimental ipython widget warning
    warnings.simplefilter("ignore")
    import seaborn as sns

    sns.set(context="paper", style="ticks", font_scale=1.5, font="Bitstream Vera Sans")
```
The issue:
https://github.com/theislab/scanpy/issues/1661 

I would suggest to remove this setting.

**Comment by ManuSetty** [comment]
Thank you Yubin. This has been updated in the v1.0.1 branch and will be changed in the next release. In the meantime, please pull from https://github.com/dpeerlab/Palantir/blob/v1.0.1/src/palantir/plot.py to avoid the conflicts.
