### ISSUE TITLE
how to find the number? start_cell = 'Run5_164698952452459

### ISSUE THREAD

**Issue by Roger-GOAT** [dpeerlab/Palantir#61]
Hi palantir team, thanks for the great work.
I have  a simple question, it maybe mention other place. How  to find the cell ID in palantir map? like in your notebook? Best!

**Comment by ManuSetty** [comment]
If you are using anndata, you can find the cell identifiers as `adata.obs_names`

**Comment by blackturtle-bam** [comment]
Hi, I also have the same question.
Could you elaborate how to use the adata.obs_names to get the cell ID? 
Sorry for such a simple question but I'm not familiar with Phyton.

**Comment by Roger-GOAT** [comment]
@ManuSetty Thank you for the reply. I know cell ID is in `adata.obs_names`. What I mean is that how to find the cell ID of one point in the map?

**Comment by ManuSetty** [comment]
I am not sure I completely understand the question. Perhaps you can try something like `tsne.index[(tsne['x'] < <val>) & (tsne['x'] > <val>)]'` to isolate the cell of interest ? You might need to add limits on `y` too.

**Comment by Roger-GOAT** [comment]
I get it, thank you @ManuSetty
