### ISSUE TITLE
MulticoreTSNE

### ISSUE THREAD

**Issue by gokceneraslan** [dpeerlab/Palantir#63]
Multicoretsne is a very problematic dependency:

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/1140359/120405967-c6171e00-c317-11eb-959c-39a93f98fac8.png">

I was wondering if it's really essential to palantir or could it be simply a runtime dependency to avoid all these issues?

**Comment by ManuSetty** [comment]
Thanks for bringing this. MulticoreTSNE is not an essential package for Palantir and we will change the dependencies. In the meantime, you can just remove the dependency and the core palantir functionality should work just fine.

**Comment by JennyWeng** [comment]
[https://github.com/DmitryUlyanov/Multicore-TSNE/issues/81#issuecomment-863745998](url)
downgrade cmake can solve the problem for me

**Comment by ManuSetty** [comment]
Thank you for your sharing your observation - can you please let us know what version of `cmake` fixed the issue?

**Comment by JennyWeng** [comment]
I found the answer on the page of Multicore-TSNE (in my previous message, copy the URL to open it in the browser, sorry for the inconvenience as I am not sure how to quote that link to here). They use ```pip install cmake==3.18.4``` and it works for me. Hope it can help others to solve the problem.

**Comment by ManuSetty** [comment]
Thank you! I am closing the issue since we have a solution
