### ISSUE TITLE
Palantir results not exactly reproducible

### ISSUE THREAD

**Issue by Marius1311** [dpeerlab/Palantir#64]
Setting the random seed does not lead to exactly reproducible results, you can easily check this in an example, just set the random seed, run palantir twice and compare the actual fate probabilities numerically, there will be slight deviations. This can only be eliminated when the waypoint cells are manually cached (written to file) and provided to palantir. In that case, results are reproducible. The deviations are really small and don't lead to e.g. different gene expression trends, however, it would still be nice to fix this bug. Thanks!

**Comment by katosh** [comment]
This should be resolved with f4970f9f0571edfed486232acb68d2f0a8c26543. It will also become available with Palantir v1.2.

**Comment by wangjiawen2013** [comment]
Great, I'll give it a try
