### ISSUE TITLE
Computing the neighborhood graph error

### ISSUE THREAD

**Issue by noobugs** [dpeerlab/Palantir#65]
Thanks for creating such a great tool!  I tested with my data following the tutorial step by step, however, when I run "sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)" always got the same err: "OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead."  I can't find a way to move forward, could you please help to check? Thank you so much!

**Comment by ManuSetty** [comment]
This looks like a environment issues. Can you perhaps try by rebuilding your conda environment.?
