### ISSUE TITLE
installation failed due to bhtsne

### ISSUE THREAD

**Issue by MichaelPeibo** [dpeerlab/Palantir#7]
Hi, 
I got stuck when I install the package.
![image](https://user-images.githubusercontent.com/32219336/57055697-9b3ce480-6ccf-11e9-8700-60543710ad5b.png)

I am using it in conda enviroment. 
I also tried to install bhtsne, still got the error
![image](https://user-images.githubusercontent.com/32219336/57055724-ca535600-6ccf-11e9-83e9-3c83279b57d5.png)

Any suggestion?
Thanks!

**Comment by ManuSetty** [comment]
I have replaced bhtsne with MulticoreTSNE to avoid these installation issues (ae0bdc0a8a0a22b18cf094c85ada01e69161dc24). Please pull the lhe latest version and try again

**Comment by MichaelPeibo** [comment]
Hi @ManuSetty , Thanks for help, it works!
