### ISSUE TITLE
FindFont No Image

### ISSUE THREAD

**Issue by Keyan719** [dpeerlab/Palantir#70]
Hi, sorry for bothering, I am trying to analyze scRNA data using this brilliant tool. However, I got some quesiton, like which version / branch shall I use to avoid the findfont warning and produce the corresponding image. I noticed that such issue had been posted in (https://github.com/dpeerlab/Palantir/issues/55). However, the solution (editted plot.py) (1) does not reflect on the master branch but in the 1.0.1 branch (2) even if I downloaded the 1.0.1 branch, (which still require MultiTSNE installation so I remove the related source code) , such error still occur. I am using the smaple csv file as input and adjusted according to this issue (https://github.com/dpeerlab/Palantir/issues/60). I attached my jupyter notebook file here. Could you please help me with this? Thanks again for developing this amazing tool.
[testing.zip](https://github.com/dpeerlab/Palantir/files/8782330/testing.zip)

**Comment by Keyan719** [comment]
I guess I kind of fixed it? I need to add a plt.savefig command within the plot_gene_expression() function to save the figure it made. It will not appear in the Jupter notebook.

**Comment by ManuSetty** [comment]
I just created a new release v1.0.1 which should address these issues: https://github.com/dpeerlab/Palantir/releases/tag/v1.0.1 

Please take a look and let us know if it works!
