### ISSUE TITLE
plot style

### ISSUE THREAD

**Issue by wangjiawen2013** [dpeerlab/Palantir#73]
Hi,
who to set the point size and font or figure size when plotting the palantir results such as palantir.plot.plot_palantir_results?

**Comment by ManuSetty** [comment]
We have unfortunately not exposed this parameter and we will do it in the future. In the meantime, you should be able to add this parameter to the function here: https://github.com/dpeerlab/Palantir/blob/c70039de69dfa01a0768623fcdbacf81b116709a/src/palantir/plot.py#L331

**Comment by ManuSetty** [comment]
This parameter has now been exposed in v1.1.0
