### ISSUE TITLE
About palantir automatically determining terminal state

### ISSUE THREAD

**Issue by galaxyeee** [dpeerlab/Palantir#74]
Dear Palantir developers,@ManuSetty

Hello, I am writing an issue because I have a question. 
I selected start cell based on high expression of the gene of interest. What I am curious about here is that palantir automatically designates the terminal state, so how do I check the cell cluster automatically designated?  
Is it possible to interpret two figures other than Pseudotime and Differentiation potential in the picture below as terminal state?

<img width="1014" alt="스크린샷 2022-06-03 오후 4 54 36" src="https://user-images.githubusercontent.com/101790387/171817180-e7558d55-0b4f-4624-b61d-f61c017e49a9.png">

Thank you.
Eunha Lim

**Comment by ManuSetty** [comment]
Yes definitely - you can interpret the branch probability titles are terminal states. The actual cells can be identified using `pr_res['branch_probs'].columns.`

**Comment by galaxyeee** [comment]
Thank you for your answer. It helped me a lot.
