### ISSUE TITLE
pypi updates

### ISSUE THREAD

**Issue by wangjiawen2013** [dpeerlab/Palantir#78]
Hi,
Plantir is not the latest version in pypi.
https://pypi.org/project/palantir/

**Comment by ManuSetty** [comment]
@andrewmoorman  Can you please help with this. Awni set this up and I am not sure how to update PyPI from Github!

**Comment by ManuSetty** [comment]
Thank you - we will have a look. In the meantime, can you please install directly from the Github repository.

**Comment by wangjiawen2013** [comment]
Now I can run palantir 1.1.0 successfully on python 3.7
