### ISSUE TITLE
Palantir results

### ISSUE THREAD

**Issue by ernohanninen** [dpeerlab/Palantir#79]
Hi!
I have few questions how to interpret the palantir results.

1. Does Palantir have a function I could use to find a list of genes which expression seems to correlate with each trajectory (one list per trajectory)?

2. Is it possible to get a matrix of pseudotime values where there would be column for cell and for the lineage the cell belongs.

3. Do you have experience to integrate Palantir results with tradeSeq? TradeSeq has a fitGAM function which has a parameter cellWeights. cellWeights is a matrix of cell weights defining the probability that a cell belongs to a particular lineage. 4. Is it possible to get such an matrix out of Palantir?

**Comment by ManuSetty** [comment]
We unfortunately do not have interfaces for the requested functionality. Here are some work arounds:
1. We have seen that using a simple spearman correlation of gene trend with lineage probability is a reliable way to identify such genes
2. These results are implicitly present in `pr_res.pseudotime` . You can extract the cells of the lineage based on lineage probabilities. 
3. The `compute_gene_trends` function (https://github.com/dpeerlab/Palantir/blob/faf2f9827dd667c6d39025b9969f8b24cf7eaf68/src/palantir/presults.py#L73) will give you these results .

**Comment by ernohanninen** [comment]
Thanks a lot! This was very helpful. With pr_res.branch_probs  function I am able to extract the terminal state probabilities, is that the same thing than lineage probability you referred in your message?

Thanks!

**Comment by ManuSetty** [comment]
It is -yes!
