### ISSUE TITLE
Unable to reproduce code from Palantir_sample_notebook.ipynb

### ISSUE THREAD

**Issue by spriyansh** [dpeerlab/Palantir#87]
Hi, I was trying to reproduce the [sample_notebook.ipynb](https://github.com/dpeerlab/Palantir/blob/79956db130b64ad3ac441a85887a51bba1e09a12/notebooks/Palantir_sample_notebook.ipynb). However, it fails at multiple steps as mentioned below,

Error: _adding a nonzero scalar to a sparse matrix is not supported. This comes in the first step of normalization
This comes in the first step of normalization
```{python}
palantir.preprocess.log_transform(ad)
```
![image](https://user-images.githubusercontent.com/34842808/196781933-b42eb3fd-cccf-4f9a-864f-57e41f1bf28c.png)

Error: _KeyError: 'x'_ (Error in the )
Unable to visualize Diffusion maps
```{python}
Palantir.plot.plot_diffusion_components(umap, dm_res)
```
![image](https://user-images.githubusercontent.com/34842808/196782094-b56b61af-b0ef-4c85-9524-c3836300da4d.png)

Error: Unable to visualize results
```{python}
palantir.plot.plot_palantir_results(pr_res, umap)
```
![image](https://user-images.githubusercontent.com/34842808/196783561-c546b22d-7a7f-44e7-a0c0-2ac202609a33.png)

Please let me know if I am using an old notebook version. I cannot find any other dedicated tutorial/walkthrough of Palantir; please let me know if it exists.

Thanks!

**Comment by ManuSetty** [comment]
Can you please try by installing Palantir from git rather than pip. We will update the pip version shortly

**Comment by spriyansh** [comment]
Hi, @ManuSetty thanks for getting back so quickly. I installed the Palantir from GitHub, and now it works fine.

However, I found that there is still an error popping up when I try to plot the terminal stated probabilities as follows,

![image](https://user-images.githubusercontent.com/34842808/197469371-8beb6bbb-b7e0-4df4-8939-5e2acfc369c9.png)

It also does not work with a single sample/cell. Is there something else that I need to update?
![image](https://user-images.githubusercontent.com/34842808/197470071-2cb8df4e-f2da-42a9-bb13-29be141ecb95.png)
![image](https://user-images.githubusercontent.com/34842808/197470117-61401856-8eb1-47af-a86b-b01606cbb970.png)

**Comment by ManuSetty** [comment]
We will look into there terminal state plotting issue very soon. For running with one state, the terminal states should still be specified as an array i.e., `['Run...']`

**Comment by ManuSetty** [comment]
Just pushed a fix for this issue.

**Comment by spriyansh** [comment]
Thanks for the response; I tried running the notebook with one run and three runs, but it now throws a different error.

![image](https://user-images.githubusercontent.com/34842808/200304422-3e6ba90a-413d-49a8-b0f2-d3eb72a2fb20.png)

I updated my conda installation of Palantir before running as follows,

```
pip install git+https://github.com/dpeerlab/Palantir.git -U
```

Do I need to do something else as well?

**Comment by ManuSetty** [comment]
The line where you are seeing the error has been updated: https://github.com/dpeerlab/Palantir/blob/4d4f9fcdbfebcf47b4ca1b7ac8a0fb1b8e5fc089/src/palantir/plot.py#L411

Perhaps the resinstall did not go through correctly? Can you try uninstalling Palantir, reinstall and try again ?

**Comment by spriyansh** [comment]
@ManuSetty yes, now it works. I did the reinstall before trying, as you suggested. Thanks, I am closing the issue as well
