### ISSUE TITLE
module 'rpy2.situation' has no attribute 'get_rlib_path'

### ISSUE THREAD

**Issue by MichaelPeibo** [dpeerlab/Palantir#9]
Hi, 
I am encountering this error, I guess it may be due to lack of some package?
However, I am too naive with rpy2, any suggestion?
Thanks!

> 
> AttributeError                            Traceback (most recent call last)
> <ipython-input-27-0c8f9b494ff0> in <module>
>       1 genes = ['CD34', 'MPO', 'GATA1', 'IRF8']
> ----> 2 gene_trends = palantir.presults.compute_gene_trends( pr_res, imp_df.loc[:, genes])
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/palantir/presults.py in compute_gene_trends(pr_res, gene_exprs, lineages, n_jobs)
>      77     try:
>      78         import rpy2
> ---> 79         import rpy2.rinterface_lib.embedded as embedded
>      80         from rpy2.robjects.packages import importr
>      81     except ImportError:
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/rpy2/rinterface_lib/embedded.py in <module>
>       5 import warnings
>       6 from _rinterface_cffi import ffi
> ----> 7 from . import openrlib
>       8 from . import callbacks
>       9 
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py in <module>
>      19 
>      20 
> ---> 21 rlib = _dlopen_rlib(R_HOME)
>      22 
>      23 
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py in _dlopen_rlib(r_home)
>      14         raise ValueError('r_home is None. '
>      15                          'Try python -m rpy2.situation')
> ---> 16     lib_path = rpy2.situation.get_rlib_path(r_home, platform.system())
>      17     rlib = ffi.dlopen(lib_path)
>      18     return rlib
> 
> AttributeError: module 'rpy2.situation' has no attribute 'get_rlib_path'

**EDITED**:
```
import rpy2
print(rpy2.__version__)
```

> 2.9.4

```
import rpy2.situation
for row in rpy2.situation.iter_info():
    print(row)

```

> Python version:
> 3.7.3 (default, Mar 27 2019, 22:11:17) 
> [GCC 7.3.0]
> Looking for R's HOME:
>     Environment variable R_HOME: None
>     Calling `R RHOME`: /home/xupb/anaconda3/lib/R
>     InstallPath in the registry: *** Only available on Windows ***
> R version:
>     In the PATH: R version 3.5.1 (2018-07-02) -- "Feather Spray"
>     Used to build rpy2: 3-5.1--74947
> Additional directories to load R packages from:
> None

**Comment by MichaelPeibo** [comment]
UPDATE:
I tried to use rpy2 3.0.4
now I got this:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-44-0c8f9b494ff0> in <module>
>       1 genes = ['CD34', 'MPO', 'GATA1', 'IRF8']
> ----> 2 gene_trends = palantir.presults.compute_gene_trends( pr_res, imp_df.loc[:, genes])
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/palantir/presults.py in compute_gene_trends(pr_res, gene_exprs, lineages, n_jobs)
>      77     try:
>      78         import rpy2
> ---> 79         import rpy2.rinterface_lib.embedded as embedded
>      80         from rpy2.robjects.packages import importr
>      81     except ImportError:
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/rpy2/rinterface_lib/embedded.py in <module>
>       5 import warnings
>       6 from _rinterface_cffi import ffi
> ----> 7 from . import openrlib
>       8 from . import callbacks
>       9 
> 
> ~/anaconda3/envs/myenv/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py in <module>
>       6 # TODO: Separate the functions in the module from the side-effect of
>       7 # finding R_HOME and opening the shared library.
> ----> 8 R_HOME = rpy2.situation.get_r_home()
>       9 
>      10 
> 
> AttributeError: module 'rpy2' has no attribute 'situation'
>

**Comment by ManuSetty** [comment]
Please try again with rpy2 version >= 3.02

**Comment by MichaelPeibo** [comment]
Great I tried to use rpy2 3.0.4 works!
