### ISSUE TITLE
Branching probabilities do not reach 1

### ISSUE THREAD

**Issue by ktpolanski** [dpeerlab/Palantir#90]
Hello,

Recently a collaborator pointed out that the branch probabilities for the terminal states are not 1. Meanwhile intuitively the end states should have branching of probabilities of 1, especially given the absorbing Markov chain. Is this some sort of quirk of the algorithm?

**Comment by ManuSetty** [comment]
Can you please provide us more details - specifically what dataset and parameters lead to this ?

**Comment by ktpolanski** [comment]
I've prepared some data: [test_pca.csv](https://github.com/dpeerlab/Palantir/files/9937751/test_pca.csv)

```python3
import palantir
import pandas as pd
import numpy as np

pcs = pd.read_csv("test_pca.csv", index_col = 0)
dm_res = palantir.utils.run_diffusion_maps(pcs, n_components=20)
ms_data = palantir.utils.determine_multiscale_space(dm_res)

pr_res = palantir.core.run_palantir(ms_data, "FCAImmP7851891-TAGTGGTGTTGCTCCT", 
                                    num_waypoints=500, knn=30, 
                                    terminal_states = ["FCAImmP7292034-GTGCGGTGTCAGAGGT", "FCA_gut8015061-GAAACTCAGCTAGTTC"])
np.max(pr_res.branch_probs)
```

**Comment by ManuSetty** [comment]
It looks like `ms_data` is picking up far too few EigenVectors and hence your results look off.  You can examine the number of chosen EigenVectors by `pd.Series(np.abs(np.diff(dm_res['EigenValues']))).sort_values(ascending=False).index` For this data, I would suggest setting the `n_eigs` parameter for `ms_data` to 7.

**Comment by ktpolanski** [comment]
Sorry, I forgot to reply here. Thank you for the answer. I followed your instructions and was able to get the terminal state branching probabilities very close to 1.

I have a number of follow up questions to try to understand this fully:
1. How did you decide on setting `n_eigs` to 7 based on the output of the call you provided? This feels like a useful diagnostic step to try to work into the Palantir workflow.
2. Why does the `n_eigs` need to be specified in `determine_multiscale_space()` specifically? Setting `n_components` in `run_diffusion_maps()` to 7 did not fix the issue, despite intuitively accomplishing something similar.
3. Technically, the probabilities are still not 1. Is there a reason for the very small gap left over?

**Comment by ManuSetty** [comment]
1. The `n_eigs` can be determined by visualizing the Eigen gap statistic ie. difference of Eigen values between successive Eigen Values. 
2. `run_diffusion_maps` determines diffusion components equal to `n_components` . `determine_multiscale_space` selects the subset to use.
3. The probabilities are computed using a subset of cells called waypoints and hence the probabilities might not be exactly 1.
