### ISSUE TITLE
start cell and pseudotime

### ISSUE THREAD

**Issue by wangjiawen2013** [dpeerlab/Palantir#92]
Hi,
It was said that "All of the algorithms require the specification of a start cell or state to orient the pseudo-time ordering" in palantir paper. we can set early_cell: Start cell for pseudotime construction in function palantir.core.run_palantir. However, I find that pseudotime of start cell don't equal to zero (0.33 in my case and 0.02 in palantir tutorial http://nbviewer.jupyter.org/github/dpeerlab/Palantir/blob/master/notebooks/Palantir_sample_notebook.ipynb
Is this pseudotime an indicator of correct start cell ? I mean, if the suitable start cell is selected, the pseudotime is approximately zero ?
so how the pseudotime of start cell calculated ?
Besides, could you explain what is waypoints ?

**Comment by ManuSetty** [comment]
The parameter `use_early_cell_as_start` https://github.com/dpeerlab/Palantir/blob/4d4f9fcdbfebcf47b4ca1b7ac8a0fb1b8e5fc089/src/palantir/core.py#L39 forces the input specified start cell to remain as the start cell. In case this parameter is set to `False`, the start is adjusted to the nearest diffusion map boundary. 

Waypoints are a subset of points sampled throughout the manifold and serve as representative points for computation of branch probabilities.
