### ISSUE TITLE
Do we need to do MAGIC imputation?

### ISSUE THREAD

**Issue by st4302** [dpeerlab/Palantir#96]
I analyzed my data using scanpy but the instructions that I found here (https://scanpy.readthedocs.io/en/stable/generated/scanpy.external.tl.palantir.html#) does not seem to include the MAGIC imputation. 
Is it ok to skip this step or should I follow the jypiter notebook on your website that includes the instructions for MAGIC?

Thank you

**Comment by ManuSetty** [comment]
Imputation is required for only for computing gene expression trends and not for Palantir itself.
