### ISSUE TITLE
Terminal states is hard to understand

### ISSUE THREAD

**Issue by liaoshengguang** [dpeerlab/Palantir#97]
Hi,

In palantir paper, "the Markov chain is also used to infer terminal states from the data. Palantir identifies terminal states as boundary cells (extrema of diffusion components) that are outliers in the stationary distribution, that is, the states into which the random walks converge (Fig. 1c)".  But sometimes we found that cells with lower/early pseudotime can be identified as terminal cells, which is hard to understand.

Here is the pseudotime
![image](https://user-images.githubusercontent.com/94089565/218994279-72960dbb-7813-4d48-8d32-624d9de87db4.png)

and here is the terminal cell
![image](https://user-images.githubusercontent.com/94089565/218994529-3f725f7f-afd1-4b6d-accb-4781215c5f85.png)

**Comment by ManuSetty** [comment]
This might be indicative of multiple terminal cells in the system. If the terminal cells are known apriori, you can specify them using the `terminal_states` parameter.

**Comment by liaoshengguang** [comment]
Sorry, my fault, the result shows just the one terminal cell, and it's far beyond the high pseudotime cells as the fig show, so that your suggestion is that i chosen a higher pseudotime cell as the terminal cell by set the terminal_states if i have no apriori knowledge.

**Comment by ManuSetty** [comment]
Given this result and since terminal states are not known, I would suggest checking Cellrank (https://cellrank.readthedocs.io/en/stable/) to see if it help in terminal state identification.

**Comment by liaoshengguang** [comment]
Thanks, i would like to test the cellrank as you mentioned.
