### ISSUE TITLE
palantir.preprocess.log_transform(ad) error

### ISSUE THREAD

**Issue by sailseem** [dpeerlab/Palantir#99]
Dear developer,

I am kind of new to this, but i found palantir really helpful for my study. But when i run this function,
 palantir.preprocess.log_transform(ad)

 i got an error      NotImplementedError: adding a nonzero scalar to a sparse matrix is not supported

I know someone brought this up before, but i am not clear how to solve it.
Sorry for this stupid question.

**Comment by ManuSetty** [comment]
We have fixed this issue in the Github repository. Please clone the repository and re-install palantir

**Comment by theDierickxLab** [comment]
I had the same problem before.  The issue was solved via git clone and reinstallation. But I still hope "pip install" can be fixed soon! Thanks a lot!

**Comment by ManuSetty** [comment]
The fixes have been uploaded to Pypi and pip install also works now.
